Repository irssi/scripts.irssi.org, pull requests merged in 2019-03, with the labels that each got.

#603 go.pl: fix short circuiting during channel search
  scripts/go.pl
Labels: invalid

#585 [oopsie] output to status window
  scripts/oopsie.pl
Labels: waiting...

#610 [rud_emotes] Added utf-8 support and auto-completion.
  scripts/rud_emotes.pl
Labels: changes requested

#600 [nickban] change the settings to irssi
  scripts/nickban.pl
Labels: waiting...
